//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GörevYöneticisiMulakatTemel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public int JobId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string JobComment { get; set; }
        public string JobType { get; set; }
        public System.DateTime JobDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
